### ISSUE TITLE
undefined method `each' for nil:NilClass with empty radiobuttons save

### ISSUE THREAD

**Issue by lemboy** [code-mancers/rapidfire#60]
If answers variants have only radiobuttons and not selected any, after Save we have "undefined method `each' for nil:NilClass" here:
```
    def save!(options = {})
      params.each do |question_id, answer_attributes|
        if answer = @answer_group.answers.find { |a| a.question_id.to_s == question_id.to_s }
          text = answer_attributes[:answer_text]
```

**Comment by iffyuva** [comment]
thanks for reporting this, i will look into it.

**Comment by iffyuva** [comment]
im able to reproduce this. the problem is more with how the view is written. when there is only 1 radio button question, and that question is not answered, then form is not submitting any values to rails server. going to dig more into this. meanwhile, can you paste the code related to your form? thanks.
